ALTER TABLE CAPITAL_MANAGER.LOGIN_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE CAPITAL_MANAGER.LOGIN_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CAPITAL_MANAGER.LOGIN_DETAILS
(
  USERID    VARCHAR2(10 BYTE),
  EMAILID   VARCHAR2(100 BYTE)                  NOT NULL,
  PASSWORD  VARCHAR2(256 BYTE)                  NOT NULL
)
TABLESPACE TBS_ANUJA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX CAPITAL_MANAGER.EMAILID_LOGIN_UNIQUE ON CAPITAL_MANAGER.LOGIN_DETAILS
(EMAILID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--  There is no statement for index CAPITAL_MANAGER.SYS_C007206.
--  The object is created when the parent object is created.

ALTER TABLE CAPITAL_MANAGER.LOGIN_DETAILS ADD (
  PRIMARY KEY
  (USERID)
  USING INDEX
    TABLESPACE TBS_ANUJA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE,
  CONSTRAINT EMAILID_LOGIN_UNIQUE
  UNIQUE (EMAILID)
  USING INDEX CAPITAL_MANAGER.EMAILID_LOGIN_UNIQUE
  ENABLE VALIDATE);

ALTER TABLE CAPITAL_MANAGER.LOGIN_DETAILS ADD (
  CONSTRAINT USERID_FK 
  FOREIGN KEY (USERID) 
  REFERENCES CAPITAL_MANAGER."USERS" (USERID)
  ENABLE VALIDATE);




ALTER TABLE CAPITAL_MANAGER."GROUP"
 DROP PRIMARY KEY CASCADE;

DROP TABLE CAPITAL_MANAGER."GROUP" CASCADE CONSTRAINTS;

CREATE TABLE CAPITAL_MANAGER."GROUP"
(
  GROUPID        VARCHAR2(10 BYTE),
  NAME           VARCHAR2(100 BYTE)             NOT NULL,
  ADMINID        VARCHAR2(10 BYTE)              NOT NULL,
  CREATION_DATE  DATE                           NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX CAPITAL_MANAGER.GROUP_PK ON CAPITAL_MANAGER."GROUP"
(GROUPID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CAPITAL_MANAGER."GROUP" ADD (
  CONSTRAINT GROUP_PK
  PRIMARY KEY
  (GROUPID)
  USING INDEX CAPITAL_MANAGER.GROUP_PK
  ENABLE VALIDATE);







ALTER TABLE CAPITAL_MANAGER."USER"
 DROP PRIMARY KEY CASCADE;

DROP TABLE CAPITAL_MANAGER."USER" CASCADE CONSTRAINTS;

CREATE TABLE CAPITAL_MANAGER."USER"
(
  USERID      VARCHAR2(10 BYTE),
  FIRSTNAME   VARCHAR2(50 BYTE)                 NOT NULL,
  MIDDLENAME  VARCHAR2(50 BYTE),
  LASTNAME    VARCHAR2(50 BYTE)                 NOT NULL,
  EMAILID     VARCHAR2(100 BYTE)                NOT NULL,
  GROUPID     VARCHAR2(10 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX CAPITAL_MANAGER.EMAILID_UNIQUE ON CAPITAL_MANAGER."USER"
(EMAILID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX CAPITAL_MANAGER.USER_PK ON CAPITAL_MANAGER."USER"
(USERID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CAPITAL_MANAGER."USER" ADD (
  CONSTRAINT USER_PK
  PRIMARY KEY
  (USERID)
  USING INDEX CAPITAL_MANAGER.USER_PK
  ENABLE VALIDATE,
  CONSTRAINT EMAILID_UNIQUE
  UNIQUE (EMAILID)
  USING INDEX CAPITAL_MANAGER.EMAILID_UNIQUE
  ENABLE VALIDATE);

ALTER TABLE CAPITAL_MANAGER."USER" ADD (
  CONSTRAINT GROUPID_FK 
  FOREIGN KEY (GROUPID) 
  REFERENCES CAPITAL_MANAGER."GROUP" (GROUPID)
  ENABLE VALIDATE);